Added fibonacci with cache, ESlint and Husky
irogozhova/learnReact pull request #2
Opened 2019-03-30 13:19 UTC by irogozhova

2019-03-30 13:22 UTC, risentveber commented on index.html
> +  <script src="./functions/tasks.js"></script>
Это зачем сделано? зачем вообще тебе на данном этапе понадобился html-файл?

2019-03-30 13:23 UTC, risentveber commented on functions/tasks.js
> +/////*\\//*\\//*\\\\\
Думаю ты забыла убрать лишние комментарии

2019-03-30 13:24 UTC, risentveber requested changes
Доработай по 2 замечаниям и подключи Travis, для запуска тестов и линтера

2019-03-31 09:44 UTC, irogozhova commented on index.html
> +  <script src="./functions/tasks.js"></script>
для логирования в консоль, лучше способа не нашла

2019-03-31 20:06 UTC, merged